import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    products: [
      {
        id: 1,
        labelPrice: 5990,
        fullPrice: 5990,
        labelPercent: 25,
        isBestSeller: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце...",
      },
      {
        id: 2,
        labelPrice: 5990,
        fullPrice: 5990,
        labelPercent: 25,
        isBestSeller: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце...",
      },
      {
        id: 3,
        labelPrice: 5990,
        fullPrice: 5990,
        labelPercent: 25,
        isBestSeller: true,
        available: false,
        name: "Полное название товара в несколько строк для вида с обрывом в конце... Полное название товара в несколько строк для вида с обрывом в конце... Полное название товара в несколько строк для вида с обрывом в конце...",
      },
      {
        id: 4,
        labelPrice: 5990,
        fullPrice: 5990,
        labelPercent: 25,
        isBestSeller: true,
        available: true,
        name: "Полное название ",
      },
      {
        id: 5,
        labelPrice: 5990,
        fullPrice: 5990,
        labelPercent: 25,
        isBestSeller: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце...",
      },
      {
        id: 6,
        labelPrice: 5990,
        fullPrice: 5990,
        labelPercent: 25,
        isBestSeller: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце...",
      },
      {
        id: 7,
        labelPrice: 5990,
        fullPrice: 5990,
        labelPercent: 25,
        isBestSeller: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце...",
      },
      {
        id: 8,
        labelPrice: 5990,
        fullPrice: 5990,
        labelPercent: 25,
        isBestSeller: true,
        available: false,
        name: "Полное название товара в несколько строк для вида с обрывом в конце...",
      },
      {
        id: 9,
        labelPrice: 5990,
        fullPrice: 5990,
        labelPercent: 25,
        isBestSeller: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце...",
      },
      {
        id: 10,
        labelPrice: 5990,
        fullPrice: 5990,
        labelPercent: 25,
        isBestSeller: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце...",
      },
      {
        id: 11,
        labelPrice: 5990,
        fullPrice: 5990,
        labelPercent: 25,
        isBestSeller: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце...",
      },
      {
        id: 12,
        labelPrice: 5990,
        fullPrice: 5990,
        labelPercent: 25,
        isBestSeller: true,
        available: true,
        name: "Полное название товара в несколько строк для вида с обрывом в конце...",
      },
    ],
  },
  getters: {},
  mutations: {},
  actions: {},
  modules: {},
});
